import { Product } from './types/Products';
export const sampleProducts: Product[] = [
  {
    name: 'Nike slim shirt',
    slug: 'nike-slim-shirt',
    category: 'shirts',
    image: '../images/p1.jpg',
    price: 500,
    countInStock: 10,
    brand: 'nike',
    rating: 4.5,
    numReviews: 25,
    description: 'high quality product',
  },
  {
    name: 'Nike slim shirt2',
    slug: 'nike-slim-shirt2w',
    category: 'shirts2',
    image: '../images/p1.jpg',
    price: 400,
    countInStock: 10,
    brand: 'nike',
    rating: 4.0,
    numReviews: 21,
    description: 'high quality product',
  },
  {
    name: 'Nike slim shirt',
    slug: 'nike-slim-shirte3',
    category: 'shirts',
    image: '../images/p1.jpg',
    price: 500,
    countInStock: 10,
    brand: 'nike',
    rating: 4.5,
    numReviews: 25,
    description: 'high quality product',
  },
  {
    name: 'Nike slim shirt2',
    slug: 'nike-slim-shirt2q',
    category: 'shirts2',
    image: '../images/p1.jpg',
    price: 400,
    countInStock: 10,
    brand: 'nike',
    rating: 4.0,
    numReviews: 21,
    description: 'high quality product',
  },
];
